project_id = "iuhndtwhvfbpswbeekht"

[functions.cron-whatsapp-reminders]
enabled = true
verify_jwt = true
entrypoint = "./functions/cron-whatsapp-reminders/index.ts"

[functions.create-user]
enabled = true
verify_jwt = true

[functions.get-user-profiles]
enabled = true
verify_jwt = true
