project_id = "iuhndtwhvfbpswbeekht"

[functions.cron-whatsapp-reminders]
enabled = true
verify_jwt = false

[functions.create-user]
enabled = true
verify_jwt = false

[functions.get-user-profiles]
enabled = true
verify_jwt = false

[functions.ai-chat]
enabled = true
verify_jwt = false

[functions.cron-billing-rules]
enabled = true
verify_jwt = false
